name: Build ReactJS App
description: 'Build ReactJS app and save to artifacts'

inputs:
  folder_name:
    description: folder to build
    required: true
  create_artifacts:
    description: indicates if create artifacts
    required: false
    default: false
    
runs:
  using: 'composite'
  steps:
    - name: build
      shell: bash
      run: |
        cd ${{ inputs.folder_name }}
        yarn install
        yarn build 
      env:
        NODE_ENV: production
        
    - name: zip_build
      shell: bash
      if: ${{ inputs.create_artifacts == 'true' }}
      run: zip -r app.zip ./${{ inputs.folder_name }}/build
      
    - name: upload_artifacts
      if: ${{ inputs.create_artifacts == 'true' }}
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ inputs.folder_name }} deployment package
        path: ./app.zip
        
